name: Cocoapods Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.3.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Run pod spec lint
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod spec lint SpotImCore.podspec --allow-warnings
        
    - name: Publish to CocoaPod
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push SpotImCore.podspec --allow-warnings
